{% set name = "gst-libav" %}
{% set version = "1.19.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-{{ version }}.tar.xz
  sha256: 6ad23508b337e91a4053321d7c49b19471b9859468d544c63148ac636472c98a
  patches:
    - ffmpeg-win.patch  # [win]

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - {{ posix }}patch  # [win]
  host:
    - ffmpeg
    - gstreamer
    - gst-plugins-base
    - glib

test:
  commands:
    - test -f ${PREFIX}/lib/gstreamer-1.0/libgstlibav${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstlibav.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin libav

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer plugin for the FFmpeg libav* libraries
  doc_url: https://gstreamer.freedesktop.org/modules/gst-libav.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-libav

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
