{% set version = "1.26.6" %}

package:
  name: gst-libav
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-{{ version }}.tar.xz
  sha256: 6e50a6222d509c52b19143f9a7bd3581e22c745d0c4bc27ddb07e1229bcc11b8

build:
  number: 3
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-libav', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - m2-patch  # [win]
  host:
    - ffmpeg
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - glib
    # Needed for gstreamer-audio-1.0 dependency?
    # Not sure why, zlib should be a private dependency
    - zlib
    - xz     # [win]
    - expat  # [win]
    - lame   # [win]
  run:
    # We want to pin harder than the run_export from gstreamer
    - gstreamer         {{ version }}
    - lame    # [win]
test:
  commands:
    - test -f ${PREFIX}/lib/gstreamer-1.0/libgstlibav${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstlibav.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin libav

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer plugin for the FFmpeg libav* libraries
  doc_url: https://gstreamer.freedesktop.org/modules/gst-libav.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-libav

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
