{% set name = "gst-libav" %}
{% set version = "1.24.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-{{ version }}.tar.xz
  sha256: d9c5b152468a45c1fa8351410422090a7192707ad74d2e1a4367f5254e188d91
  patches:
    - ffmpeg-win.patch  # [win]

build:
  number: 1
  skip: true  # [osx]
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-libav', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - {{ posix }}patch  # [win]
  host:
    - ffmpeg
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - glib
    # Needed for gstreamer-audio-1.0 dependency?
    # Not sure why, zlib should be a private dependency
    - zlib
  run:
    # We want to pin harder than the run_export from gstreamer
    - gstreamer         {{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/gstreamer-1.0/libgstlibav${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstlibav.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin libav

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer plugin for the FFmpeg libav* libraries
  doc_url: https://gstreamer.freedesktop.org/modules/gst-libav.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-libav

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
