{% set name = "gst-libav" %}
{% set version = "1.22.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-{{ version }}.tar.xz
  sha256: 7789e6408388a25f23cbf948cfc5c6230d735bbcd8b7f37f4a01c9e348a1e3a7
  patches:
    - ffmpeg-win.patch  # [win]

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-libav', max_pin='x.x') }}

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - {{ posix }}patch  # [win]
  host:
    - ffmpeg
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - glib
    # Needed for gstreamer-audio-1.0 dependency?
    # Not sure why, zlib should be a private dependency
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/gstreamer-1.0/libgstlibav${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstlibav.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin libav

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer plugin for the FFmpeg libav* libraries
  doc_url: https://gstreamer.freedesktop.org/modules/gst-libav.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-libav

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
